### ISSUE TITLE
No content visible in AInspector under Fx 52.0a2

### ISSUE THREAD

**Issue by Cliabhach** [ainspector/issues#1]
TOOL: AInspector Sidebar

VERSION: 1.0.0

RULESET: HTML5/ARIA Techniques

DESCRIPTION: Information does not populate, the following errors appear in the browser console:

Error 1:
```
TypeError: window.content is null[Learn More]               ai-sidebar.js:111:3
ainspectorSidebar.updateContext chrome://ai-sidebar/content/ai-sidebar.js:111:3
```

Error 2:

    [Exception... "Security Manager vetoed action"  nsresult: "0x80570027 (NS_ERROR_XPC_SECURITY_MANAGER_VETO)" location: "JS frame :: chrome://ai-sidebar/content/ai-sidebar.js :: ainspectorSidebar.clearCurrentView :: line 698"  data: no] (unknown)

Method name | call site
-------------------------------------------------------|------------------------------------------------------
ainspectorSidebar.clearCurrentView | chrome://ai-sidebar/content/ai-sidebar.js:698:1
ainspectorSidebar.showTransition | chrome://ai-sidebar/content/ai-sidebar.js:95:3
getProgressListener/<.onLocationChange | chrome://ai-sidebar/content/utilities/progress.js:60:9
wrapProgressListener/ListenerHandler.get/< | resource://gre/modules/RemoteAddonsParent.jsm:939:11
callListeners | chrome://browser/content/tabbrowser.xml:506:24
_callProgressListeners | chrome://browser/content/tabbrowser.xml:521:13
mTabProgressListener/<._callProgressListeners | chrome://browser/content/tabbrowser.xml:576:22
mTabProgressListener/<.onLocationChange | chrome://browser/content/tabbrowser.xml:829:17
RemoteWebProgressManager.prototype._callProgressListeners | resource://gre/modules/RemoteWebProgress.jsm:176:11
RemoteWebProgressManager.prototype.receiveMessage | resource://gre/modules/RemoteWebProgress.jsm:259:7

Firefox Developer Edition (52.0a2 2017-01-09 64-bit, E10s enabled)
Mac OS X 10.10.5

URL: `www.google.com`, `www.mozilla.org`, probably others

STEPS TO REPRODUCE:
1. Ensure AInspector Sidebar is closed.
2. Navigate to an affected url.
3. Note the appearance of `Error 1` in the browser console.
4. Navigate to a different affected url (by e.g. entering said url into the address bar and pressing enter)
5. Note the appearance of `Error 2` in the browser console.

**Comment by nhoyt** [comment]
This is a known problem. AInspector Sidebar does not support multiprocess Firefox (aka e10s enabled).

The workaround is:
1. In the FirefoxDeveloperEdition menu select Preferences
2. Under the General tab, uncheck: Enable multi-process Firefox Developer Edition.

**Comment by Cliabhach** [comment]
Cool, thanks for explaining that.
